# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "npower-app"
client_id = "50fdfca1b98e8df24a6e4c6903c63e23"
application_url = "https://bears-nt-www-afraid.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,read_customers"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://bears-nt-www-afraid.trycloudflare.com/auth/callback",
  "https://bears-nt-www-afraid.trycloudflare.com/auth/shopify/callback",
  "https://bears-nt-www-afraid.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dangkhoa2520.myshopify.com"
